version: 2
updates:
  # .NET 8 NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 15
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "deps(.NET 8)"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"
    target-branch: "main"
    # Block major version updates (e.g., .NET 8 → 9)
    ignore:
      - dependency-name: "Microsoft.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group Markdown processing libraries
      markdown-processing:
        patterns:
          - "Markdig"
          - "Markdig.*"
        update-types:
          - "minor"
          - "patch"
      # Group ASP.NET Core 8 packages (framework updates)
      aspnetcore-framework:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.*"
        update-types:
          - "patch"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "main"

  # Docker dependencies (.NET 8 runtime)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "docker(.NET 8)"
    labels:
      - "dependencies"
      - "docker"
    target-branch: "main"
    groups:
      # Group .NET Docker images
      dotnet-runtime:
        patterns:
          - "mcr.microsoft.com/dotnet/aspnet"
          - "mcr.microsoft.com/dotnet/sdk"
        update-types:
          - "minor"
          - "patch"