version: 2
updates:
  # .NET NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 15
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"
    groups:
      # Group Blazor/ASP.NET Core components
      blazor-aspnet:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.AspNetCore.Components*"
          - "Microsoft.JSInterop"
      # Group Microsoft extensions and hosting
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.Extensions.Hosting*"
          - "Microsoft.Extensions.DependencyInjection*"
          - "Microsoft.Extensions.Configuration*"
          - "Microsoft.Extensions.Http*"
      # Group HTTP and API client libraries
      http-clients:
        patterns:
          - "System.Net.Http*"
          - "System.Text.Json"
          - "Newtonsoft.Json"
      # Group content processing libraries
      content-processing:
        patterns:
          - "Markdig*"
          - "System.Text.*"
      # Group testing frameworks
      testing:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "NUnit*"
          - "Moq"
          - "FluentAssertions"
          - "Microsoft.AspNetCore.Mvc.Testing"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies (if using Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "JustDanMan"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"