name: Build and Dockerize on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release -o ./publish

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images (lowercase repo name)
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG_NAME=${{ github.event.release.tag_name }}

          echo "Building image: $IMAGE_NAME:$TAG_NAME"
          docker build -t $IMAGE_NAME:$TAG_NAME .

          echo "Tagging as latest..."
          docker tag $IMAGE_NAME:$TAG_NAME $IMAGE_NAME:latest

          echo "Pushing $TAG_NAME..."
          docker push $IMAGE_NAME:$TAG_NAME

          echo "Pushing latest..."
          docker push $IMAGE_NAME:latest